/* Hollowmere: the quest pool. Villagers hand these out one at a time, picked at random from the
 * quests that fit the story so far (stage) and the areas already open. Each quest is played by the
 * game's own systems, so none can get stuck:
 *   kill    defeat n foes of one kind in a zone
 *   collect pick up n items that appear in a zone (they appear again until you have them all)
 *   rescue  find someone in a zone and talk to them (they go home), then return to the giver
 *   deliver take something to another villager, then return to the giver
 *   elite   defeat a named, much stronger foe that waits in a zone
 * Rewards are worked out by the game from your level and the kind of quest.
 * Texts: title, offer (the giver asks), goal ({n}/{m} = progress), done (thanks), found / given. */
window.HM_POOL = [
// ---------------------------------------------------------------- Bram, the woodcutter (the Greywood)
{ id: 'b1', giver: 'bram', type: 'kill', foe: 'wolf', n: 6, zone: 'greywood', stage: 1, t: {
    en: { title: 'Pack Hunt', offer: 'The wolves are back at the woodpile, bolder than ever. Six of them would make the rest think twice.', goal: 'Defeat wolves in the Greywood ({n}/{m}).', done: 'Quiet nights again. My axe thanks you.' },
    fr: { title: 'Chasse à la meute', offer: 'Les loups sont revenus près du bûcher, plus hardis que jamais. En abattre six ferait réfléchir les autres.', goal: 'Vainquez des loups dans le Boisgris ({n}/{m}).', done: 'Des nuits calmes, enfin. Ma hache vous remercie.' },
    es: { title: 'Caza de la manada', offer: 'Los lobos han vuelto a la leñera, más atrevidos que nunca. Seis menos harían pensar al resto.', goal: 'Derrota lobos en el Bosquegrís ({n}/{m}).', done: 'Por fin noches tranquilas. Mi hacha te lo agradece.' },
    ar: { title: 'صيد القطيع', offer: 'عادت الذئاب إلى كومة الحطب، أجرأ من أي وقت مضى. ستة منها ستجعل البقية تفكّر مرتين.', goal: 'اهزموا الذئاب في الغابة الرمادية ({n}/{m}).', done: 'ليالٍ هادئة من جديد. فأسي تشكركم.' } } },
{ id: 'b2', giver: 'bram', type: 'collect', icon: 'resin', n: 4, zone: 'greywood', stage: 1, t: {
    en: { title: 'Pine Resin', offer: 'The old pines weep resin when the Hush is near. Gather four lumps and I can make torches that never sputter.', goal: 'Gather pine resin in the Greywood ({n}/{m}).', done: 'Good, sticky resin. These torches will burn till morning.' },
    fr: { title: 'Résine de pin', offer: 'Les vieux pins pleurent de la résine quand le Silence approche. Ramassez-en quatre morceaux et je ferai des torches qui ne crachotent jamais.', goal: 'Ramassez de la résine dans le Boisgris ({n}/{m}).', done: 'De la bonne résine bien collante. Ces torches brûleront jusqu\'au matin.' },
    es: { title: 'Resina de pino', offer: 'Los pinos viejos lloran resina cuando el Silencio se acerca. Recoge cuatro trozos y haré antorchas que nunca chisporrotean.', goal: 'Recoge resina en el Bosquegrís ({n}/{m}).', done: 'Buena resina, bien pegajosa. Estas antorchas arderán hasta el amanecer.' },
    ar: { title: 'راتنج الصنوبر', offer: 'تذرف أشجار الصنوبر القديمة راتنجًا حين يقترب السكون. اجمعوا أربع كتل وسأصنع مشاعل لا تنطفئ.', goal: 'اجمعوا راتنج الصنوبر في الغابة الرمادية ({n}/{m}).', done: 'راتنج جيد ولزج. ستشتعل هذه المشاعل حتى الصباح.' } } },
{ id: 'b3', giver: 'bram', type: 'elite', foe: 'wolf', zone: 'greywood', stage: 2, name: { en: 'Old Greymaw', fr: 'Vieille Gueule-Grise', es: 'Viejo Fauces Grises', ar: 'الفكّ الرمادي العجوز' }, t: {
    en: { title: 'Old Greymaw', offer: 'There is a wolf with a scar across its muzzle, as big as a pony. It leads the others. End it, and the pack will scatter.', goal: 'Defeat Old Greymaw in the Greywood.', done: 'Greymaw, gone at last. I\'ll sleep with both eyes closed tonight.' },
    fr: { title: 'Vieille Gueule-Grise', offer: 'Il y a un loup avec une cicatrice sur le museau, grand comme un poney. Il mène les autres. Abattez-le, et la meute se dispersera.', goal: 'Vainquez Vieille Gueule-Grise dans le Boisgris.', done: 'Gueule-Grise n\'est plus. Je dormirai les deux yeux fermés ce soir.' },
    es: { title: 'Viejo Fauces Grises', offer: 'Hay un lobo con una cicatriz en el hocico, grande como un poni. Guía a los demás. Acaba con él y la manada se dispersará.', goal: 'Derrota al Viejo Fauces Grises en el Bosquegrís.', done: 'Fauces Grises, por fin. Esta noche dormiré con los dos ojos cerrados.' },
    ar: { title: 'الفكّ الرمادي العجوز', offer: 'هناك ذئب بندبة على خطمه، بحجم مهر صغير. إنه يقود الآخرين. اقضوا عليه، وسيتفرّق القطيع.', goal: 'اهزموا الفكّ الرمادي العجوز في الغابة الرمادية.', done: 'رحل الفكّ الرمادي أخيرًا. سأنام الليلة مغمض العينين.' } } },
{ id: 'b4', giver: 'bram', type: 'kill', foe: 'bones', n: 6, zone: 'barrow', stage: 4, t: {
    en: { title: 'Restless Dead', offer: 'Since the Barrow opened, I hear bones rattling under the roots. Put six of them back to sleep, would you?', goal: 'Defeat skeletons in the Barrow Crypt ({n}/{m}).', done: 'The roots are quiet again. Thank you, and wash your hands.' },
    fr: { title: 'Morts sans repos', offer: 'Depuis que le Tertre est ouvert, j\'entends des os cliqueter sous les racines. Rendormez-en six, voulez-vous ?', goal: 'Vainquez des squelettes dans la Crypte du Tertre ({n}/{m}).', done: 'Les racines se taisent de nouveau. Merci, et lavez-vous les mains.' },
    es: { title: 'Muertos inquietos', offer: 'Desde que se abrió el Túmulo, oigo huesos traqueteando bajo las raíces. ¿Puedes volver a dormir a seis?', goal: 'Derrota esqueletos en la Cripta del Túmulo ({n}/{m}).', done: 'Las raíces vuelven a estar en silencio. Gracias, y lávate las manos.' },
    ar: { title: 'موتى بلا راحة', offer: 'منذ فُتح التلّ، أسمع عظامًا تقرقع تحت الجذور. هل تعيدون ستة منها إلى النوم؟', goal: 'اهزموا الهياكل العظمية في سرداب التلّ ({n}/{m}).', done: 'هدأت الجذور من جديد. شكرًا لكم، واغسلوا أيديكم.' } } },
{ id: 'b5', giver: 'bram', type: 'collect', icon: 'axe', n: 3, zone: 'greywood', stage: 2, t: {
    en: { title: 'Lost Axe Heads', offer: 'Three of my axe heads flew off their handles when the wolves came. They are somewhere in the wood, shining like fish.', goal: 'Find Bram\'s axe heads in the Greywood ({n}/{m}).', done: 'My axes, whole again! A woodcutter without an axe is just a man in a forest.' },
    fr: { title: 'Fers de hache perdus', offer: 'Trois de mes fers de hache se sont envolés quand les loups sont venus. Ils sont quelque part dans le bois, brillants comme des poissons.', goal: 'Retrouvez les fers de hache de Bram dans le Boisgris ({n}/{m}).', done: 'Mes haches, entières ! Un bûcheron sans hache, c\'est juste un homme dans une forêt.' },
    es: { title: 'Hachas perdidas', offer: 'Tres de mis cabezas de hacha salieron volando cuando llegaron los lobos. Están en algún lugar del bosque, brillando como peces.', goal: 'Encuentra las cabezas de hacha de Bram en el Bosquegrís ({n}/{m}).', done: '¡Mis hachas, enteras otra vez! Un leñador sin hacha es solo un hombre en un bosque.' },
    ar: { title: 'رؤوس الفؤوس الضائعة', offer: 'طارت ثلاثة من رؤوس فؤوسي حين جاءت الذئاب. إنها في مكان ما في الغابة، تلمع كالأسماك.', goal: 'ابحثوا عن رؤوس فؤوس برام في الغابة الرمادية ({n}/{m}).', done: 'فؤوسي كاملة من جديد! الحطّاب بلا فأس مجرّد رجل في غابة.' } } },
// ---------------------------------------------------------------- Hana, the potion seller (the Mirefen)
{ id: 'h1', giver: 'hana', type: 'collect', icon: 'cap', n: 5, zone: 'mireshore', stage: 6, t: {
    en: { title: 'More Glowcaps', offer: 'My best potions need glowcaps, and they sprout again every night on the Mirefen shore. Five, please.', goal: 'Gather glowcaps on the Mirefen shore ({n}/{m}).', done: 'Blue and glowing, perfect. Your next potion is half-price in my heart.' },
    fr: { title: 'Encore des luminelles', offer: 'Mes meilleures potions ont besoin de luminelles, et elles repoussent chaque nuit sur la rive de la Fangemare. Cinq, s\'il vous plaît.', goal: 'Cueillez des luminelles sur la rive de la Fangemare ({n}/{m}).', done: 'Bleues et lumineuses, parfait. Votre prochaine potion est à moitié prix dans mon cœur.' },
    es: { title: 'Más lucetas', offer: 'Mis mejores pociones necesitan lucetas, y vuelven a brotar cada noche en la orilla de Lodomar. Cinco, por favor.', goal: 'Recoge lucetas en la orilla de Lodomar ({n}/{m}).', done: 'Azules y brillantes, perfectas. Tu próxima poción es a mitad de precio en mi corazón.' },
    ar: { title: 'مزيد من الفطر المتوهّج', offer: 'أفضل جرعاتي تحتاج إلى الفطر المتوهّج، وهو ينبت من جديد كل ليلة على شاطئ ميرفن. خمس حبّات من فضلكم.', goal: 'اجمعوا الفطر المتوهّج على شاطئ ميرفن ({n}/{m}).', done: 'زرقاء ومتوهّجة، ممتاز. جرعتكم القادمة بنصف السعر في قلبي.' } } },
{ id: 'h2', giver: 'hana', type: 'kill', foe: 'crawler', n: 8, zone: 'isle', stage: 9, t: {
    en: { title: 'Crawler Nest', offer: 'The crawlers on the Drowned Isle are breeding in the reeds. Eight fewer, and my herb beds might survive the season.', goal: 'Defeat crawlers on the Drowned Isle ({n}/{m}).', done: 'Eight! You\'re braver than my cat, and my cat fights geese.' },
    fr: { title: 'Nid de rampeurs', offer: 'Les rampeurs de l\'Île Noyée se multiplient dans les roseaux. Huit de moins, et mes plates-bandes survivront peut-être à la saison.', goal: 'Vainquez des rampeurs sur l\'Île Noyée ({n}/{m}).', done: 'Huit ! Vous êtes plus courageux que mon chat, et mon chat se bat contre des oies.' },
    es: { title: 'Nido de reptadores', offer: 'Los reptadores de la Isla Ahogada se multiplican entre los juncos. Ocho menos, y quizá mis hierbas sobrevivan a la temporada.', goal: 'Derrota reptadores en la Isla Ahogada ({n}/{m}).', done: '¡Ocho! Eres más valiente que mi gato, y mi gato pelea con gansos.' },
    ar: { title: 'عشّ الزواحف', offer: 'الزواحف في الجزيرة الغارقة تتكاثر بين القصب. ثمانية أقل، وقد تنجو أحواض أعشابي هذا الموسم.', goal: 'اهزموا الزواحف في الجزيرة الغارقة ({n}/{m}).', done: 'ثمانية! أنتم أشجع من قطّي، وقطّي يقاتل الإوزّ.' } } },
{ id: 'h3', giver: 'hana', type: 'deliver', to: 'sela', stage: 6, t: {
    en: { title: 'A Remedy for Sela', offer: 'Sela\'s cough has been rattling across the mire for a week. Take her this tonic, and don\'t let her pour it in the water.', goal: 'Take Hana\'s tonic to Sela on the Mirefen shore.', given: 'Hana sent this? Hmph. Tell her I\'ll drink it... probably.', done: 'She took it? Ha! Then she must be really ill. Thank you.' },
    fr: { title: 'Un remède pour Sela', offer: 'La toux de Sela résonne sur le marais depuis une semaine. Portez-lui ce tonique, et ne la laissez pas le verser dans l\'eau.', goal: 'Portez le tonique de Hana à Sela, sur la rive de la Fangemare.', given: 'C\'est Hana qui l\'envoie ? Hmf. Dites-lui que je le boirai... sûrement.', done: 'Elle l\'a pris ? Ha ! Alors elle doit être vraiment malade. Merci.' },
    es: { title: 'Un remedio para Sela', offer: 'La tos de Sela retumba por la ciénaga desde hace una semana. Llévale este tónico, y no dejes que lo tire al agua.', goal: 'Lleva el tónico de Hana a Sela, en la orilla de Lodomar.', given: '¿Lo manda Hana? Hmf. Dile que me lo tomaré... seguramente.', done: '¿Lo aceptó? ¡Ja! Entonces debe de estar muy enferma. Gracias.' },
    ar: { title: 'دواء لسيلا', offer: 'سعال سيلا يتردّد فوق المستنقع منذ أسبوع. خذوا لها هذا المقوّي، ولا تدعوها تسكبه في الماء.', goal: 'خذوا مقوّي هانا إلى سيلا على شاطئ ميرفن.', given: 'هانا أرسلته؟ همم. قولوا لها إنني سأشربه... على الأرجح.', done: 'أخذته؟ ها! إذن لا بدّ أنها مريضة حقًا. شكرًا لكم.' } } },
{ id: 'h4', giver: 'hana', type: 'collect', icon: 'moss', n: 4, zone: 'isle', stage: 9, t: {
    en: { title: 'Moon Moss', offer: 'Moon moss only grows where drowned bells ring. You know the place. Four tufts, and I can brew something special.', goal: 'Gather moon moss on the Drowned Isle ({n}/{m}).', done: 'Still silver! Moon moss fades so fast. You were quick.' },
    fr: { title: 'Mousse de lune', offer: 'La mousse de lune ne pousse que là où sonnent les cloches noyées. Vous connaissez l\'endroit. Quatre touffes, et je pourrai préparer quelque chose de spécial.', goal: 'Cueillez de la mousse de lune sur l\'Île Noyée ({n}/{m}).', done: 'Encore argentée ! La mousse de lune pâlit si vite. Vous avez fait vite.' },
    es: { title: 'Musgo lunar', offer: 'El musgo lunar solo crece donde suenan las campanas ahogadas. Ya conoces el sitio. Cuatro matas, y podré preparar algo especial.', goal: 'Recoge musgo lunar en la Isla Ahogada ({n}/{m}).', done: '¡Todavía plateado! El musgo lunar se apaga muy rápido. Has sido veloz.' },
    ar: { title: 'طحلب القمر', offer: 'لا ينمو طحلب القمر إلا حيث تدقّ الأجراس الغارقة. تعرفون المكان. أربع خصلات، وسأحضّر شيئًا مميّزًا.', goal: 'اجمعوا طحلب القمر في الجزيرة الغارقة ({n}/{m}).', done: 'ما زال فضّيًا! طحلب القمر يبهت بسرعة. كنتم سريعين.' } } },
{ id: 'h5', giver: 'hana', type: 'elite', foe: 'crawler', zone: 'mireshore', stage: 7, name: { en: 'The Bog Mother', fr: 'La Mère du Marais', es: 'La Madre del Fango', ar: 'أمّ المستنقع' }, t: {
    en: { title: 'The Bog Mother', offer: 'There is a crawler on the shore as big as a barrel. The others follow her everywhere. If she goes, they\'ll wander off.', goal: 'Defeat the Bog Mother on the Mirefen shore.', done: 'The Bog Mother! I\'d hug you, but you smell of mud.' },
    fr: { title: 'La Mère du Marais', offer: 'Il y a sur la rive un rampeur gros comme un tonneau. Les autres la suivent partout. Si elle disparaît, ils s\'éparpilleront.', goal: 'Vainquez la Mère du Marais sur la rive de la Fangemare.', done: 'La Mère du Marais ! Je vous serrerais bien dans mes bras, mais vous sentez la boue.' },
    es: { title: 'La Madre del Fango', offer: 'Hay un reptador en la orilla grande como un barril. Los demás la siguen a todas partes. Si ella cae, se dispersarán.', goal: 'Derrota a la Madre del Fango en la orilla de Lodomar.', done: '¡La Madre del Fango! Te daría un abrazo, pero hueles a barro.' },
    ar: { title: 'أمّ المستنقع', offer: 'على الشاطئ زاحفة بحجم برميل. الباقون يتبعونها في كل مكان. إن ذهبت، سيتفرّقون.', goal: 'اهزموا أمّ المستنقع على شاطئ ميرفن.', done: 'أمّ المستنقع! كنت سأعانقكم، لكن رائحتكم وحل.' } } },
// ---------------------------------------------------------------- Odo, the guard (the quarry and the mine)
{ id: 'o1', giver: 'odo', type: 'kill', foe: 'mite', n: 8, zone: 'quarry', stage: 11, t: {
    en: { title: 'Gnawed Gate', offer: 'The mites are chewing the gate again. Eight of them, and I\'ll stop hearing that crunching in my sleep.', goal: 'Defeat stone mites in the Old Quarry ({n}/{m}).', done: 'No more crunching. You have my thanks, and my ears\' thanks too.' },
    fr: { title: 'Grille rongée', offer: 'Les mites rongent encore la grille. Huit d\'entre elles, et je n\'entendrai plus ce craquement dans mon sommeil.', goal: 'Vainquez des mites de pierre dans la Vieille Carrière ({n}/{m}).', done: 'Plus de craquements. Vous avez mes remerciements, et ceux de mes oreilles.' },
    es: { title: 'La verja roída', offer: 'Los ácaros vuelven a roer la verja. Ocho de ellos, y dejaré de oír ese crujido en sueños.', goal: 'Derrota ácaros de piedra en la Vieja Cantera ({n}/{m}).', done: 'Se acabó el crujido. Tienes mi gratitud, y la de mis oídos.' },
    ar: { title: 'البوابة المقضومة', offer: 'السوس يقضم البوابة مرة أخرى. ثمانية منه، ولن أسمع ذلك الطقطقة في نومي.', goal: 'اهزموا سوس الصخر في المقلع القديم ({n}/{m}).', done: 'لا مزيد من الطقطقة. لكم شكري، وشكر أذنيّ أيضًا.' } } },
{ id: 'o2', giver: 'odo', type: 'elite', foe: 'mite', zone: 'quarry', stage: 11, name: { en: 'Grindjaw', fr: 'Broie-Mâchoire', es: 'Muelemandíbulas', ar: 'الطاحن' }, t: {
    en: { title: 'Grindjaw', offer: 'One mite in the quarry is the size of a cart, and it ate my spare helmet. Its name is Grindjaw now. I named it. Out of spite.', goal: 'Defeat Grindjaw in the Old Quarry.', done: 'Grindjaw is gravel. I\'ll sleep with my helmet on tonight anyway.' },
    fr: { title: 'Broie-Mâchoire', offer: 'Une mite de la carrière est grosse comme une charrette, et elle a mangé mon casque de rechange. Elle s\'appelle Broie-Mâchoire. C\'est moi qui l\'ai nommée. Par rancune.', goal: 'Vainquez Broie-Mâchoire dans la Vieille Carrière.', done: 'Broie-Mâchoire n\'est plus que du gravier. Je dormirai quand même avec mon casque ce soir.' },
    es: { title: 'Muelemandíbulas', offer: 'Un ácaro de la cantera es del tamaño de un carro, y se comió mi yelmo de repuesto. Se llama Muelemandíbulas. Le puse el nombre yo. Por rencor.', goal: 'Derrota a Muelemandíbulas en la Vieja Cantera.', done: 'Muelemandíbulas es grava. Igualmente, esta noche dormiré con el yelmo puesto.' },
    ar: { title: 'الطاحن', offer: 'في المقلع سوسة بحجم عربة، وقد أكلت خوذتي الاحتياطية. اسمها الآن الطاحن. أنا من سمّاها. نكاية بها.', goal: 'اهزموا الطاحن في المقلع القديم.', done: 'صار الطاحن حصى. ومع ذلك سأنام الليلة بخوذتي.' } } },
{ id: 'o3', giver: 'odo', type: 'rescue', zone: 'mine', stage: 11, who: { look: 'miner', name: { en: 'Pell', fr: 'Pell', es: 'Pell', ar: 'بيل' } }, t: {
    en: { title: 'The Lost Miner', offer: 'Old Pell went down the mine to find his lucky pick. That was this morning. He\'s too stubborn to come back up without it.', goal: 'Find Pell somewhere in the Deep Mine.', found: 'My lucky pick was in my belt the whole time. Don\'t tell anyone. I\'ll find my own way out!', done: 'Pell\'s back, grumbling about his pick. Thank you for going down there.' },
    fr: { title: 'Le mineur perdu', offer: 'Le vieux Pell est descendu dans la mine chercher sa pioche porte-bonheur. C\'était ce matin. Il est trop têtu pour remonter sans elle.', goal: 'Retrouvez Pell quelque part dans la Mine Profonde.', found: 'Ma pioche porte-bonheur était dans ma ceinture depuis le début. Ne le dites à personne. Je retrouverai la sortie tout seul !', done: 'Pell est revenu, en ronchonnant à propos de sa pioche. Merci d\'être descendus.' },
    es: { title: 'El minero perdido', offer: 'El viejo Pell bajó a la mina a buscar su pico de la suerte. Fue esta mañana. Es demasiado terco para subir sin él.', goal: 'Encuentra a Pell en algún lugar de la Mina Profunda.', found: 'Mi pico de la suerte estaba en mi cinturón todo el tiempo. No se lo digas a nadie. ¡Ya encuentro yo la salida!', done: 'Pell ha vuelto, refunfuñando por su pico. Gracias por bajar a buscarlo.' },
    ar: { title: 'عامل المنجم التائه', offer: 'نزل العجوز بيل إلى المنجم ليبحث عن معوله الجالب للحظ. كان ذلك هذا الصباح. إنه أعند من أن يصعد من دونه.', goal: 'ابحثوا عن بيل في مكان ما من المنجم العميق.', found: 'كان معولي في حزامي طوال الوقت. لا تخبروا أحدًا. سأجد طريقي إلى الخارج بنفسي!', done: 'عاد بيل يتذمّر من معوله. شكرًا لنزولكم إلى هناك.' } } },
{ id: 'o4', giver: 'odo', type: 'kill', foe: 'bat', n: 8, zone: 'mine', stage: 11, t: {
    en: { title: 'Bats in the Belfry', offer: 'Bats from the mine fly out every night and steal the guards\' supper. Eight of them, and we eat in peace.', goal: 'Defeat bats in the Deep Mine ({n}/{m}).', done: 'Supper is safe! Have a sausage. Have two.' },
    fr: { title: 'Chauves-souris', offer: 'Les chauves-souris de la mine sortent chaque nuit et volent le dîner des gardes. Huit d\'entre elles, et on mangera en paix.', goal: 'Vainquez des chauves-souris dans la Mine Profonde ({n}/{m}).', done: 'Le dîner est sauvé ! Prenez une saucisse. Prenez-en deux.' },
    es: { title: 'Murciélagos', offer: 'Los murciélagos de la mina salen cada noche y roban la cena de los guardias. Ocho de ellos, y cenaremos en paz.', goal: 'Derrota murciélagos en la Mina Profunda ({n}/{m}).', done: '¡La cena está a salvo! Toma una salchicha. Toma dos.' },
    ar: { title: 'خفافيش الليل', offer: 'تخرج خفافيش المنجم كل ليلة وتسرق عشاء الحرّاس. ثمانية منها، ونأكل بسلام.', goal: 'اهزموا الخفافيش في المنجم العميق ({n}/{m}).', done: 'العشاء بأمان! خذوا نقانق. خذوا اثنتين.' } } },
{ id: 'o5', giver: 'odo', type: 'deliver', to: 'tobin', stage: 1, t: {
    en: { title: 'The Patrol Report', offer: 'I can\'t leave my post, and Tobin needs to know what\'s moving near the gate. Take him my report, would you?', goal: 'Take Odo\'s report to Tobin at the forge.', given: 'More mites, more wolves... Odo writes like he swings a spear. Straight to the point.', done: 'He read it? Good. Now the forge knows what the gate knows.' },
    fr: { title: 'Le rapport de patrouille', offer: 'Je ne peux pas quitter mon poste, et Tobin doit savoir ce qui rôde près de la grille. Vous lui portez mon rapport ?', goal: 'Portez le rapport d\'Odo à Tobin, à la forge.', given: 'Plus de mites, plus de loups... Odo écrit comme il manie la lance. Droit au but.', done: 'Il l\'a lu ? Bien. Maintenant la forge sait ce que sait la grille.' },
    es: { title: 'El informe de patrulla', offer: 'No puedo dejar mi puesto, y Tobin tiene que saber qué se mueve cerca de la verja. ¿Le llevas mi informe?', goal: 'Lleva el informe de Odo a Tobin, a la forja.', given: 'Más ácaros, más lobos... Odo escribe como maneja la lanza. Directo al grano.', done: '¿Lo leyó? Bien. Ahora la forja sabe lo que sabe la verja.' },
    ar: { title: 'تقرير الدورية', offer: 'لا أستطيع ترك موقعي، وتوبين يجب أن يعرف ما يتحرّك قرب البوابة. هل تأخذون إليه تقريري؟', goal: 'خذوا تقرير أودو إلى توبين في الكور.', given: 'مزيد من السوس، مزيد من الذئاب... أودو يكتب كما يطعن برمحه. مباشرة إلى الهدف.', done: 'قرأه؟ جيد. الآن يعرف الكور ما تعرفه البوابة.' } } },
// ---------------------------------------------------------------- Pip, the boy (the village and the Greywood)
{ id: 'p1', giver: 'pip', type: 'collect', icon: 'feather', n: 4, zone: 'greywood', stage: 1, t: {
    en: { title: 'Feathers for a Kite', offer: 'I\'m building the biggest kite in Hollowmere! I need four long feathers from the Greywood. Owls drop the best ones.', goal: 'Find long feathers in the Greywood ({n}/{m}).', done: 'Look how long they are! My kite will reach the clouds. Maybe the moon.' },
    fr: { title: 'Des plumes pour un cerf-volant', offer: 'Je construis le plus grand cerf-volant de Hollowmere ! Il me faut quatre longues plumes du Boisgris. Les chouettes perdent les meilleures.', goal: 'Trouvez de longues plumes dans le Boisgris ({n}/{m}).', done: 'Regardez comme elles sont longues ! Mon cerf-volant touchera les nuages. Peut-être la lune.' },
    es: { title: 'Plumas para una cometa', offer: '¡Estoy haciendo la cometa más grande de Hollowmere! Necesito cuatro plumas largas del Bosquegrís. Los búhos sueltan las mejores.', goal: 'Encuentra plumas largas en el Bosquegrís ({n}/{m}).', done: '¡Mira qué largas son! Mi cometa llegará a las nubes. Quizá a la luna.' },
    ar: { title: 'ريش لطائرة ورقية', offer: 'أصنع أكبر طائرة ورقية في هولومير! أحتاج إلى أربع ريشات طويلة من الغابة الرمادية. البوم يُسقط أفضلها.', goal: 'ابحثوا عن ريش طويل في الغابة الرمادية ({n}/{m}).', done: 'انظروا كم هي طويلة! ستصل طائرتي إلى الغيوم. ربما إلى القمر.' } } },
{ id: 'p2', giver: 'pip', type: 'deliver', to: 'maren', stage: 1, t: {
    en: { title: 'A Drawing for Maren', offer: 'I drew Elder Maren lighting the Lantern. Can you give it to her? I\'m too shy. Don\'t look at the nose, it went wrong.', goal: 'Take Pip\'s drawing to Elder Maren.', given: 'Oh, Pip drew this? Look at that nose. It\'s perfect. I\'m keeping it forever.', done: 'She liked it? She liked the nose? Yes!' },
    fr: { title: 'Un dessin pour Maren', offer: 'J\'ai dessiné l\'Ancienne Maren en train d\'allumer la Lanterne. Vous pouvez le lui donner ? Je suis trop timide. Ne regardez pas le nez, il est raté.', goal: 'Portez le dessin de Pip à l\'Ancienne Maren.', given: 'Oh, c\'est Pip qui a dessiné ça ? Regardez ce nez. Il est parfait. Je le garde pour toujours.', done: 'Ça lui a plu ? Le nez aussi ? Ouais !' },
    es: { title: 'Un dibujo para Maren', offer: 'He dibujado a la Anciana Maren encendiendo el Farol. ¿Se lo das? Me da vergüenza. No mires la nariz, me salió mal.', goal: 'Lleva el dibujo de Pip a la Anciana Maren.', given: 'Oh, ¿esto lo dibujó Pip? Mira esa nariz. Es perfecta. Lo guardaré para siempre.', done: '¿Le gustó? ¿Le gustó la nariz? ¡Sí!' },
    ar: { title: 'رسمة لمارين', offer: 'رسمت الحكيمة مارين وهي تُشعل الفانوس. هل تعطونها إياها؟ أنا خجول جدًا. لا تنظروا إلى الأنف، لقد أفسدته.', goal: 'خذوا رسمة بيب إلى الحكيمة مارين.', given: 'أوه، بيب رسم هذا؟ انظروا إلى ذلك الأنف. إنه مثالي. سأحتفظ بها إلى الأبد.', done: 'أعجبتها؟ أعجبها الأنف؟ نعم!' } } },
{ id: 'p3', giver: 'pip', type: 'collect', icon: 'shell', n: 5, zone: 'mireshore', stage: 6, t: {
    en: { title: 'Shiny Shells', offer: 'Biscuit and I are making a treasure collection. The best shells are on the Mirefen shore. Five shiny ones, please!', goal: 'Find shiny shells on the Mirefen shore ({n}/{m}).', done: 'This one has a rainbow inside! Biscuit, look! Biscuit is not looking.' },
    fr: { title: 'Coquillages brillants', offer: 'Biscuit et moi, on fait une collection de trésors. Les plus beaux coquillages sont sur la rive de la Fangemare. Cinq brillants, s\'il vous plaît !', goal: 'Trouvez des coquillages brillants sur la rive de la Fangemare ({n}/{m}).', done: 'Celui-là a un arc-en-ciel dedans ! Biscuit, regarde ! Biscuit ne regarde pas.' },
    es: { title: 'Conchas brillantes', offer: 'Galleta y yo estamos haciendo una colección de tesoros. Las mejores conchas están en la orilla de Lodomar. ¡Cinco brillantes, por favor!', goal: 'Encuentra conchas brillantes en la orilla de Lodomar ({n}/{m}).', done: '¡Esta tiene un arcoíris dentro! ¡Galleta, mira! Galleta no está mirando.' },
    ar: { title: 'أصداف لامعة', offer: 'أنا وبسكويت نصنع مجموعة كنوز. أفضل الأصداف على شاطئ ميرفن. خمس أصداف لامعة من فضلكم!', goal: 'ابحثوا عن أصداف لامعة على شاطئ ميرفن ({n}/{m}).', done: 'هذه فيها قوس قزح! بسكويت، انظر! بسكويت لا ينظر.' } } },
{ id: 'p4', giver: 'pip', type: 'rescue', zone: 'greywood', stage: 2, who: { look: 'kid', name: { en: 'Wynn', fr: 'Wynn', es: 'Wynn', ar: 'وين' } }, t: {
    en: { title: 'Hide and Seek', offer: 'Wynn and I were playing hide and seek, and Wynn hid in the Greywood. That\'s cheating! And now Wynn won\'t come out.', goal: 'Find Wynn hiding in the Greywood.', found: 'You found me! Nobody ever finds me. Okay, okay, I\'ll go home. Tell Pip I won.', done: 'Wynn says they won. They did NOT win. Thank you though!' },
    fr: { title: 'Cache-cache', offer: 'Wynn et moi, on jouait à cache-cache, et Wynn s\'est caché dans le Boisgris. C\'est de la triche ! Et maintenant Wynn ne veut plus sortir.', goal: 'Trouvez Wynn, caché dans le Boisgris.', found: 'Vous m\'avez trouvé ! Personne ne me trouve jamais. D\'accord, d\'accord, je rentre. Dites à Pip que j\'ai gagné.', done: 'Wynn dit avoir gagné. C\'est FAUX. Merci quand même !' },
    es: { title: 'El escondite', offer: 'Wynn y yo jugábamos al escondite, y Wynn se escondió en el Bosquegrís. ¡Eso es trampa! Y ahora no quiere salir.', goal: 'Encuentra a Wynn escondido en el Bosquegrís.', found: '¡Me encontraste! Nadie me encuentra nunca. Vale, vale, me voy a casa. Dile a Pip que gané.', done: 'Wynn dice que ganó. NO ganó. ¡Pero gracias!' },
    ar: { title: 'الغمّيضة', offer: 'كنت ألعب الغمّيضة مع وين، فاختبأ وين في الغابة الرمادية. هذا غشّ! والآن لا يريد الخروج.', goal: 'ابحثوا عن وين المختبئ في الغابة الرمادية.', found: 'وجدتموني! لا أحد يجدني أبدًا. حسنًا، حسنًا، سأعود إلى البيت. قولوا لبيب إنني فزت.', done: 'وين يقول إنه فاز. لم يفز أبدًا. لكن شكرًا لكم!' } } },
{ id: 'p5', giver: 'pip', type: 'kill', foe: 'wisp', n: 8, zone: 'greywood', stage: 1, t: {
    en: { title: 'Ghost Hunter', offer: 'Are the grey ghosts in the wood scary? I\'m not scared. Biscuit is scared. Could you get rid of eight of them, for Biscuit?', goal: 'Defeat Hush wisps in the Greywood ({n}/{m}).', done: 'Eight ghosts! I\'m telling everyone you\'re a ghost hunter now. It\'s official.' },
    fr: { title: 'Chasseur de fantômes', offer: 'Les fantômes gris du bois, ils font peur ? Moi, j\'ai pas peur. Biscuit a peur. Vous pourriez en chasser huit, pour Biscuit ?', goal: 'Vainquez des feux du Silence dans le Boisgris ({n}/{m}).', done: 'Huit fantômes ! Je vais dire à tout le monde que vous êtes chasseur de fantômes. C\'est officiel.' },
    es: { title: 'Cazafantasmas', offer: '¿Dan miedo los fantasmas grises del bosque? Yo no tengo miedo. Galleta tiene miedo. ¿Puedes librarte de ocho, por Galleta?', goal: 'Derrota fuegos del Silencio en el Bosquegrís ({n}/{m}).', done: '¡Ocho fantasmas! Voy a decirle a todos que eres cazafantasmas. Es oficial.' },
    ar: { title: 'صائد الأشباح', offer: 'هل الأشباح الرمادية في الغابة مخيفة؟ أنا لست خائفًا. بسكويت خائف. هل تتخلّصون من ثمانية منها، من أجل بسكويت؟', goal: 'اهزموا أطياف السكون في الغابة الرمادية ({n}/{m}).', done: 'ثمانية أشباح! سأخبر الجميع أنكم صائدو أشباح الآن. رسميًا.' } } },
// ---------------------------------------------------------------- Sela, the ferrywoman (the Mirefen and the isle)
{ id: 's1', giver: 'sela', type: 'kill', foe: 'crawler', n: 6, zone: 'mireshore', stage: 6, t: {
    en: { title: 'Mud on the Dock', offer: 'Crawlers keep climbing onto my dock and leaving slime on the planks. Six of them, and the boat stays clean.', goal: 'Defeat crawlers on the Mirefen shore ({n}/{m}).', done: 'Clean planks. The mire gives, the mire takes, and today it took the crawlers.' },
    fr: { title: 'De la boue sur le ponton', offer: 'Les rampeurs grimpent sur mon ponton et laissent de la bave sur les planches. Six d\'entre eux, et la barque restera propre.', goal: 'Vainquez des rampeurs sur la rive de la Fangemare ({n}/{m}).', done: 'Des planches propres. Le marais donne, le marais prend, et aujourd\'hui il a pris les rampeurs.' },
    es: { title: 'Barro en el embarcadero', offer: 'Los reptadores suben a mi embarcadero y dejan baba en las tablas. Seis de ellos, y la barca seguirá limpia.', goal: 'Derrota reptadores en la orilla de Lodomar ({n}/{m}).', done: 'Tablas limpias. La ciénaga da, la ciénaga quita, y hoy se llevó a los reptadores.' },
    ar: { title: 'وحل على الرصيف', offer: 'الزواحف تتسلّق رصيفي وتترك لزوجتها على الألواح. ستة منها، ويبقى القارب نظيفًا.', goal: 'اهزموا الزواحف على شاطئ ميرفن ({n}/{m}).', done: 'ألواح نظيفة. المستنقع يعطي ويأخذ، واليوم أخذ الزواحف.' } } },
{ id: 's2', giver: 'sela', type: 'collect', icon: 'lamp', n: 3, zone: 'isle', stage: 9, t: {
    en: { title: 'Drowned Lanterns', offer: 'Ferry lamps from the old days wash up on the Drowned Isle. Bring me three. Every one of them carried someone home once.', goal: 'Find old ferry lanterns on the Drowned Isle ({n}/{m}).', done: 'Three old friends. I\'ll hang them on the dock, so the drowned can see the way.' },
    fr: { title: 'Lanternes noyées', offer: 'Les lampes des anciens bacs s\'échouent sur l\'Île Noyée. Rapportez-m\'en trois. Chacune a ramené quelqu\'un chez lui, autrefois.', goal: 'Trouvez de vieilles lanternes de bac sur l\'Île Noyée ({n}/{m}).', done: 'Trois vieilles amies. Je les accrocherai au ponton, pour que les noyés voient le chemin.' },
    es: { title: 'Faroles ahogados', offer: 'Los faroles de las barcas de antaño aparecen en la Isla Ahogada. Tráeme tres. Cada uno llevó a alguien a casa alguna vez.', goal: 'Encuentra viejos faroles de barca en la Isla Ahogada ({n}/{m}).', done: 'Tres viejos amigos. Los colgaré en el embarcadero, para que los ahogados vean el camino.' },
    ar: { title: 'فوانيس غارقة', offer: 'فوانيس المعدّيات القديمة يقذفها الماء إلى الجزيرة الغارقة. أحضروا لي ثلاثة. كل واحد منها أعاد أحدهم إلى بيته ذات يوم.', goal: 'ابحثوا عن فوانيس المعدّيات القديمة في الجزيرة الغارقة ({n}/{m}).', done: 'ثلاثة أصدقاء قدامى. سأعلّقها على الرصيف، كي يرى الغرقى الطريق.' } } },
{ id: 's3', giver: 'sela', type: 'elite', foe: 'wisp', zone: 'isle', stage: 9, name: { en: 'The Pale Lady', fr: 'La Dame Pâle', es: 'La Dama Pálida', ar: 'السيدة الشاحبة' }, t: {
    en: { title: 'The Pale Lady', offer: 'A cold light walks the Drowned Isle at dusk, humming the bell\'s song. The old ferrymen called her the Pale Lady. Send her to rest.', goal: 'Defeat the Pale Lady on the Drowned Isle.', done: 'The humming stopped. I didn\'t know how loud it was until it was gone.' },
    fr: { title: 'La Dame Pâle', offer: 'Une lumière froide marche sur l\'Île Noyée au crépuscule, en fredonnant le chant de la cloche. Les anciens passeurs l\'appelaient la Dame Pâle. Donnez-lui le repos.', goal: 'Vainquez la Dame Pâle sur l\'Île Noyée.', done: 'Le fredonnement s\'est tu. Je ne savais pas qu\'il était si fort avant qu\'il disparaisse.' },
    es: { title: 'La Dama Pálida', offer: 'Una luz fría recorre la Isla Ahogada al anochecer, tarareando la canción de la campana. Los viejos barqueros la llamaban la Dama Pálida. Dale descanso.', goal: 'Derrota a la Dama Pálida en la Isla Ahogada.', done: 'El tarareo se detuvo. No sabía lo fuerte que era hasta que desapareció.' },
    ar: { title: 'السيدة الشاحبة', offer: 'ضوء بارد يمشي في الجزيرة الغارقة عند الغسق، يدندن لحن الجرس. سمّاها المعدّيون القدامى السيدة الشاحبة. امنحوها الراحة.', goal: 'اهزموا السيدة الشاحبة في الجزيرة الغارقة.', done: 'توقّفت الدندنة. لم أكن أعرف كم كانت عالية حتى رحلت.' } } },
{ id: 's4', giver: 'sela', type: 'rescue', zone: 'mireshore', stage: 6, who: { look: 'fisher', name: { en: 'Dob', fr: 'Dob', es: 'Dob', ar: 'دوب' } }, t: {
    en: { title: 'Dob in the Reeds', offer: 'Dob the fisherman went into the reeds after a giant eel. His boat came back without him. Find him.', goal: 'Find Dob the fisherman on the Mirefen shore.', found: 'The eel! It was THIS big! ...Fine, it was a log. I\'m going home before anyone hears about this.', done: 'Dob\'s home, telling everyone about his eel. It was a log, wasn\'t it?' },
    fr: { title: 'Dob dans les roseaux', offer: 'Dob le pêcheur est parti dans les roseaux après une anguille géante. Sa barque est revenue sans lui. Retrouvez-le.', goal: 'Retrouvez Dob le pêcheur sur la rive de la Fangemare.', found: 'L\'anguille ! Elle était GRANDE comme ça ! ...Bon, c\'était un tronc. Je rentre avant que quelqu\'un l\'apprenne.', done: 'Dob est rentré, et il raconte son anguille à tout le monde. C\'était un tronc, hein ?' },
    es: { title: 'Dob entre los juncos', offer: 'Dob el pescador se metió entre los juncos tras una anguila gigante. Su barca volvió sin él. Encuéntralo.', goal: 'Encuentra a Dob el pescador en la orilla de Lodomar.', found: '¡La anguila! ¡Era ASÍ de grande! ...Vale, era un tronco. Me voy a casa antes de que se entere alguien.', done: 'Dob está en casa, contando lo de su anguila. Era un tronco, ¿verdad?' },
    ar: { title: 'دوب بين القصب', offer: 'دخل دوب الصيّاد بين القصب يلاحق ثعبان ماء عملاقًا. عاد قاربه من دونه. ابحثوا عنه.', goal: 'ابحثوا عن دوب الصيّاد على شاطئ ميرفن.', found: 'الثعبان! كان بهذا الحجم! ...حسنًا، كان جذع شجرة. سأعود إلى البيت قبل أن يسمع أحد بهذا.', done: 'دوب في بيته يحكي للجميع عن ثعبانه. كان جذع شجرة، أليس كذلك؟' } } },
{ id: 's5', giver: 'sela', type: 'deliver', to: 'hana', stage: 6, t: {
    en: { title: 'Fresh Catch', offer: 'Hana pays for mire-perch, and I\'ve no time to walk to the village. Take her this basket before it starts to smell.', goal: 'Take Sela\'s basket of fish to Hana in the village.', given: 'Mire-perch! Sela remembered. These make the best broth for tired heroes.', done: 'Hana paid? Then here\'s your share. Fish money spends like any other.' },
    fr: { title: 'Pêche fraîche', offer: 'Hana paie pour la perche des marais, et je n\'ai pas le temps d\'aller au village. Portez-lui ce panier avant qu\'il ne sente.', goal: 'Portez le panier de poissons de Sela à Hana, au village.', given: 'De la perche des marais ! Sela s\'en est souvenue. Ça fait le meilleur bouillon pour les héros fatigués.', done: 'Hana a payé ? Alors voici votre part. L\'argent du poisson vaut bien l\'autre.' },
    es: { title: 'Pesca fresca', offer: 'Hana paga por la perca del pantano, y no tengo tiempo de ir al pueblo. Llévale esta cesta antes de que empiece a oler.', goal: 'Lleva la cesta de pescado de Sela a Hana, al pueblo.', given: '¡Perca del pantano! Sela se acordó. Hace el mejor caldo para héroes cansados.', done: '¿Hana pagó? Entonces aquí tienes tu parte. El dinero del pescado vale como cualquier otro.' },
    ar: { title: 'صيد طازج', offer: 'هانا تدفع ثمن فرخ المستنقع، وليس لديّ وقت للمشي إلى القرية. خذوا إليها هذه السلّة قبل أن تفوح رائحتها.', goal: 'خذوا سلّة سمك سيلا إلى هانا في القرية.', given: 'فرخ المستنقع! تذكّرت سيلا. هذا يصنع أفضل حساء للأبطال المتعبين.', done: 'دفعت هانا؟ إذن هذه حصّتكم. مال السمك يُنفق كأي مال آخر.' } } },
// ---------------------------------------------------------------- Tobin, the blacksmith (the forge, the mine, the Barrow)
{ id: 't1', giver: 'tobin', type: 'collect', icon: 'coal', n: 5, zone: 'mine', stage: 11, t: {
    en: { title: 'Coal for the Forge', offer: 'My coal pile is down to dust, and the Deep Mine still has the good black stuff lying in the tunnels. Five lumps.', goal: 'Collect coal in the Deep Mine ({n}/{m}).', done: 'Now that\'s coal. You can hear it wanting to burn.' },
    fr: { title: 'Du charbon pour la forge', offer: 'Mon tas de charbon n\'est plus que poussière, et la Mine Profonde a encore du bon charbon noir dans ses tunnels. Cinq morceaux.', goal: 'Ramassez du charbon dans la Mine Profonde ({n}/{m}).', done: 'Ça, c\'est du charbon. On l\'entend presque vouloir brûler.' },
    es: { title: 'Carbón para la forja', offer: 'Mi montón de carbón se ha quedado en polvo, y la Mina Profunda aún tiene del bueno tirado en los túneles. Cinco trozos.', goal: 'Recoge carbón en la Mina Profunda ({n}/{m}).', done: 'Eso sí es carbón. Casi se le oye querer arder.' },
    ar: { title: 'فحم للكور', offer: 'كومة فحمي صارت غبارًا، والمنجم العميق ما زال فيه فحم أسود جيد ملقى في الأنفاق. خمس كتل.', goal: 'اجمعوا الفحم في المنجم العميق ({n}/{m}).', done: 'هذا هو الفحم. تكاد تسمعه يريد الاشتعال.' } } },
{ id: 't2', giver: 'tobin', type: 'elite', foe: 'bones', zone: 'barrow', stage: 4, name: { en: 'The Iron Revenant', fr: 'Le Revenant de fer', es: 'El Aparecido de Hierro', ar: 'العائد الحديدي' }, t: {
    en: { title: 'The Iron Revenant', offer: 'Someone saw a skeleton in the Barrow wearing armour from my grandfather\'s forge. I\'d like that armour to stop walking around.', goal: 'Defeat the Iron Revenant in the Barrow Crypt.', done: 'Grandfather\'s work, still holding up after all this time. A shame about the owner.' },
    fr: { title: 'Le Revenant de fer', offer: 'Quelqu\'un a vu dans le Tertre un squelette portant une armure de la forge de mon grand-père. J\'aimerais que cette armure arrête de se promener.', goal: 'Vainquez le Revenant de fer dans la Crypte du Tertre.', done: 'Le travail de grand-père tient toujours, après tout ce temps. Dommage pour le propriétaire.' },
    es: { title: 'El Aparecido de Hierro', offer: 'Alguien vio en el Túmulo un esqueleto con una armadura de la forja de mi abuelo. Me gustaría que esa armadura dejara de pasearse.', goal: 'Derrota al Aparecido de Hierro en la Cripta del Túmulo.', done: 'El trabajo del abuelo, aún aguanta después de tanto tiempo. Lástima del dueño.' },
    ar: { title: 'العائد الحديدي', offer: 'رأى أحدهم في التلّ هيكلًا عظميًا يرتدي درعًا من كور جدّي. أودّ أن يتوقّف ذلك الدرع عن التجوّل.', goal: 'اهزموا العائد الحديدي في سرداب التلّ.', done: 'صنعة جدّي ما زالت صامدة بعد كل هذا الوقت. يا للأسف على صاحبها.' } } },
{ id: 't3', giver: 'tobin', type: 'kill', foe: 'bones', n: 8, zone: 'mine', stage: 11, t: {
    en: { title: 'Clearing the Tunnels', offer: 'If I\'m to mine star iron again, the tunnels need clearing. Old bones walk down there. Eight of them, for a start.', goal: 'Defeat skeletons in the Deep Mine ({n}/{m}).', done: 'Clear tunnels. The miners will buy you a drink. Several drinks.' },
    fr: { title: 'Nettoyer les tunnels', offer: 'Si je dois de nouveau extraire du fer-étoile, il faut nettoyer les tunnels. De vieux os y marchent. Huit d\'entre eux, pour commencer.', goal: 'Vainquez des squelettes dans la Mine Profonde ({n}/{m}).', done: 'Des tunnels propres. Les mineurs vous paieront un verre. Plusieurs verres.' },
    es: { title: 'Limpiar los túneles', offer: 'Si voy a volver a extraer hierro estelar, hay que limpiar los túneles. Por allí caminan huesos viejos. Ocho, para empezar.', goal: 'Derrota esqueletos en la Mina Profunda ({n}/{m}).', done: 'Túneles limpios. Los mineros te invitarán a una copa. A varias.' },
    ar: { title: 'تنظيف الأنفاق', offer: 'إن كنت سأستخرج الحديد النجمي من جديد، فالأنفاق تحتاج إلى تنظيف. عظام قديمة تمشي هناك. ثمانية منها، كبداية.', goal: 'اهزموا الهياكل العظمية في المنجم العميق ({n}/{m}).', done: 'أنفاق نظيفة. سيدعوكم عمّال المنجم إلى شراب. إلى عدّة أشربة.' } } },
{ id: 't4', giver: 'tobin', type: 'deliver', to: 'odo', stage: 4, t: {
    en: { title: 'Odo\'s New Spear', offer: 'Odo\'s spear was chewed by mites, poor man. I\'ve made him a new one. Take it to him at the north gate.', goal: 'Take the new spear to Odo at the north gate.', given: 'A new spear! Look at that edge. The mites will learn to fear me now.', done: 'He liked it? He\'d better. That\'s my best spear in ten years.' },
    fr: { title: 'La nouvelle lance d\'Odo', offer: 'La lance d\'Odo a été rongée par les mites, le pauvre. Je lui en ai fait une nouvelle. Portez-la-lui à la grille nord.', goal: 'Portez la nouvelle lance à Odo, à la grille nord.', given: 'Une nouvelle lance ! Regardez ce fil. Les mites vont apprendre à me craindre.', done: 'Elle lui a plu ? Il vaudrait mieux. C\'est ma meilleure lance depuis dix ans.' },
    es: { title: 'La lanza nueva de Odo', offer: 'Los ácaros royeron la lanza de Odo, pobre hombre. Le he hecho una nueva. Llévasela a la verja norte.', goal: 'Lleva la lanza nueva a Odo, a la verja norte.', given: '¡Una lanza nueva! Mira ese filo. Ahora los ácaros aprenderán a temerme.', done: '¿Le gustó? Más le vale. Es mi mejor lanza en diez años.' },
    ar: { title: 'رمح أودو الجديد', offer: 'قضم السوس رمح أودو، المسكين. صنعت له رمحًا جديدًا. خذوه إليه عند البوابة الشمالية.', goal: 'خذوا الرمح الجديد إلى أودو عند البوابة الشمالية.', given: 'رمح جديد! انظروا إلى هذا الحدّ. سيتعلّم السوس أن يخافني الآن.', done: 'أعجبه؟ يُستحسن ذلك. إنه أفضل رمح صنعته منذ عشر سنين.' } } },
{ id: 't5', giver: 'tobin', type: 'collect', icon: 'scrap', n: 4, zone: 'barrow', stage: 4, t: {
    en: { title: 'Old Armour', offer: 'The Barrow is full of old armour scraps. Good metal, just old. Bring me four pieces and I\'ll melt them into something new.', goal: 'Collect old armour scraps in the Barrow Crypt ({n}/{m}).', done: 'Old metal remembers being useful. It\'ll be glad to work again.' },
    fr: { title: 'Vieilles armures', offer: 'Le Tertre est plein de morceaux de vieilles armures. Du bon métal, juste vieux. Rapportez-m\'en quatre et je les fondrai en quelque chose de neuf.', goal: 'Ramassez des morceaux d\'armure dans la Crypte du Tertre ({n}/{m}).', done: 'Le vieux métal se souvient d\'avoir été utile. Il sera content de reprendre du service.' },
    es: { title: 'Armadura vieja', offer: 'El Túmulo está lleno de trozos de armaduras viejas. Buen metal, solo que viejo. Tráeme cuatro piezas y las fundiré en algo nuevo.', goal: 'Recoge trozos de armadura en la Cripta del Túmulo ({n}/{m}).', done: 'El metal viejo recuerda haber sido útil. Se alegrará de volver a trabajar.' },
    ar: { title: 'دروع قديمة', offer: 'التلّ مليء بقطع الدروع القديمة. معدن جيد، لكنه قديم. أحضروا لي أربع قطع وسأصهرها في شيء جديد.', goal: 'اجمعوا قطع الدروع القديمة في سرداب التلّ ({n}/{m}).', done: 'المعدن القديم يتذكّر أنه كان نافعًا. سيسعده أن يعمل من جديد.' } } }
];
